/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ConsumerBilling;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.text.*;
import java.awt.print.*;
import java.util.Calendar;
import javax.swing.JTextField;


/**
 *
 * @author Lenovo
 */
public class Consumer_Billing extends javax.swing.JFrame {

    String iTax, iSubTotal,iTotal;
    double[] itemcost= new double[20];
    public Consumer_Billing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtxtSurname = new javax.swing.JTextField();
        jtxtPostCode = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtCustomerRef = new javax.swing.JTextField();
        jtxtCustomerMo = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jLocaleChooser3 = new com.toedter.components.JLocaleChooser();
        jLocaleChooser4 = new com.toedter.components.JLocaleChooser();
        jLocaleChooser5 = new com.toedter.components.JLocaleChooser();
        jPanel8 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnTotal = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jChkFan = new javax.swing.JCheckBox();
        jChkLights = new javax.swing.JCheckBox();
        jChkMicrowaveoven = new javax.swing.JCheckBox();
        jChkAirConditioner = new javax.swing.JCheckBox();
        jChkSofa = new javax.swing.JCheckBox();
        jChkBed = new javax.swing.JCheckBox();
        jChkRefrigerator = new javax.swing.JCheckBox();
        jChkChair = new javax.swing.JCheckBox();
        jChkTelivision = new javax.swing.JCheckBox();
        jChkIron = new javax.swing.JCheckBox();
        jtxtAirConditioner = new javax.swing.JTextField();
        jtxtMicrowaveoven = new javax.swing.JTextField();
        jtxtTelivision = new javax.swing.JTextField();
        jtxtBed = new javax.swing.JTextField();
        jtxtSofa = new javax.swing.JTextField();
        jtxtChair = new javax.swing.JTextField();
        jtxtRefrigerator = new javax.swing.JTextField();
        jtxtFan = new javax.swing.JTextField();
        jtxtLights = new javax.swing.JTextField();
        jtxtIron = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jbtnPrint = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 224, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(176, 224, 230));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Customer Mobile:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 220, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Post Code:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Address1:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Surname:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Firstname:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Customer Ref:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 140, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Nationality");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Email:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Gender:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("ID Type:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Date of Birth:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jtxtSurname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSurnameActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 140, -1));

        jtxtPostCode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPostCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPostCodeActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 140, -1));

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAddressActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 140, -1));

        jtxtFirstname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirstnameActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 140, -1));

        jtxtCustomerRef.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCustomerRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCustomerRefActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtCustomerRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 140, -1));

        jtxtCustomerMo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCustomerMo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCustomerMoActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtCustomerMo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 140, -1));

        jtxtEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 140, -1));

        jLocaleChooser3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Transgender", "Rather not say" }));
        jPanel2.add(jLocaleChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 150, 20));

        jLocaleChooser4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Passport", "Driving License", "Aadhar Card", "PAN Card", "ID card" }));
        jLocaleChooser4.setDoubleBuffered(true);
        jPanel2.add(jLocaleChooser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 150, 20));

        jLocaleChooser5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Canada", "India", "USA", "Switzerland", "Poland", "Germany", "Russia", "Thailand", "Japan", "China", "Peru", "Australia", "New Zealand", "UAE", " " }));
        jLocaleChooser5.setAutoscrolls(true);
        jPanel2.add(jLocaleChooser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 150, 20));

        jPanel8.setBackground(new java.awt.Color(176, 224, 230));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 120, 80));

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, 80));

        jPanel9.setBackground(new java.awt.Color(176, 224, 230));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setText("Reset");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 120, 80));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton12.setText("Exit");
        jPanel9.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 120, 80));

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton13.setText("Total");
        jPanel9.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, 80));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 400, 160));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 390, 170));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 430, 730));

        jPanel5.setBackground(new java.awt.Color(176, 224, 230));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(176, 224, 230));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jChkFan.setBackground(new java.awt.Color(176, 224, 230));
        jChkFan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jChkFan.setText("Fan");
        jChkFan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkFanActionPerformed(evt);
            }
        });
        jPanel3.add(jChkFan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jChkLights.setBackground(new java.awt.Color(176, 224, 230));
        jChkLights.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jChkLights.setText("Lights");
        jChkLights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkLightsActionPerformed(evt);
            }
        });
        jPanel3.add(jChkLights, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jChkMicrowaveoven.setBackground(new java.awt.Color(176, 224, 230));
        jChkMicrowaveoven.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jChkMicrowaveoven.setText("Microwave oven");
        jChkMicrowaveoven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkMicrowaveovenActionPerformed(evt);
            }
        });
        jPanel3.add(jChkMicrowaveoven, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jChkAirConditioner.setBackground(new java.awt.Color(176, 224, 230));
        jChkAirConditioner.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jChkAirConditioner.setText("Air Conditioner");
        jChkAirConditioner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkAirConditionerActionPerformed(evt);
            }
        });
        jPanel3.add(jChkAirConditioner, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jChkSofa.setBackground(new java.awt.Color(176, 224, 230));
        jChkSofa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jChkSofa.setText("Sofa");
        jChkSofa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkSofaActionPerformed(evt);
            }
        });
        jPanel3.add(jChkSofa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jChkBed.setBackground(new java.awt.Color(176, 224, 230));
        jChkBed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jChkBed.setText("Bed");
        jChkBed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkBedActionPerformed(evt);
            }
        });
        jPanel3.add(jChkBed, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jChkRefrigerator.setBackground(new java.awt.Color(176, 224, 230));
        jChkRefrigerator.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jChkRefrigerator.setText("Refrigerator");
        jChkRefrigerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkRefrigeratorActionPerformed(evt);
            }
        });
        jPanel3.add(jChkRefrigerator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jChkChair.setBackground(new java.awt.Color(176, 224, 230));
        jChkChair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jChkChair.setText("Chair");
        jChkChair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkChairActionPerformed(evt);
            }
        });
        jPanel3.add(jChkChair, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jChkTelivision.setBackground(new java.awt.Color(176, 224, 230));
        jChkTelivision.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jChkTelivision.setText("Telivision");
        jChkTelivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkTelivisionActionPerformed(evt);
            }
        });
        jPanel3.add(jChkTelivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jChkIron.setBackground(new java.awt.Color(176, 224, 230));
        jChkIron.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jChkIron.setText("Iron");
        jChkIron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkIronActionPerformed(evt);
            }
        });
        jPanel3.add(jChkIron, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jtxtAirConditioner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtAirConditioner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAirConditionerActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtAirConditioner, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 140, 30));

        jtxtMicrowaveoven.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtMicrowaveoven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMicrowaveovenActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtMicrowaveoven, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 140, 30));

        jtxtTelivision.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTelivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTelivisionActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtTelivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 140, 30));

        jtxtBed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtBed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBedActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtBed, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 140, 30));
        jtxtBed.getAccessibleContext().setAccessibleName("");

        jtxtSofa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtSofa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSofaActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtSofa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 140, 30));

        jtxtChair.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChairActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtChair, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 140, 30));

        jtxtRefrigerator.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtRefrigerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtRefrigeratorActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtRefrigerator, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 140, 30));

        jtxtFan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFanActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtFan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 140, 30));

        jtxtLights.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtLights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLightsActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtLights, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 140, 30));

        jtxtIron.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtIron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIronActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtIron, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 140, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Tax Paid");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 240, 50));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Sub Total");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 90, 60));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 140, 30));

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 140, 30));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 140, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Total Cost");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 130, 50));

        jLabel19.setBackground(new java.awt.Color(95, 150, 160));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel19.setText("Tax and Total Sum");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 380, 40));

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 680));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 470, 730));

        jPanel4.setBackground(new java.awt.Color(176, 224, 230));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(176, 224, 230));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, 80));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 120, 80));

        jPanel7.setBackground(new java.awt.Color(176, 224, 230));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 120, 80));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Exit");
        jPanel7.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 120, 80));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Total");
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, 80));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 400, 160));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 400, 160));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setRows(5);
        jtxtReceipt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtxtReceiptPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jtxtReceipt);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 400, 490));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 440, 730));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1430, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtTelivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTelivisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTelivisionActionPerformed

    private void jtxtMicrowaveovenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMicrowaveovenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMicrowaveovenActionPerformed

    private void jtxtAirConditionerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAirConditionerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAirConditionerActionPerformed

    private void jChkSofaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkSofaActionPerformed
        if(jChkSofa.isSelected())
        {
            jtxtSofa.setEnabled(true);
            jtxtSofa.setText("");
            jtxtSofa.requestFocus();
        }
        else
        {
           jtxtSofa.setEnabled(false);
           jtxtSofa.setText("0");
        }
    }//GEN-LAST:event_jChkSofaActionPerformed

    private void jChkRefrigeratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkRefrigeratorActionPerformed
         if(jChkRefrigerator.isSelected())
        {
            jtxtRefrigerator.setEnabled(true);
            jtxtRefrigerator.setText("");
            jtxtRefrigerator.requestFocus();
        }
        else
        {
           jtxtRefrigerator.setEnabled(false);
           jtxtRefrigerator.setText("0");
        }
    }//GEN-LAST:event_jChkRefrigeratorActionPerformed

    private void jChkLightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkLightsActionPerformed
        if(jChkLights.isSelected())
        {
            jtxtLights.setEnabled(true);
            jtxtLights.setText("");
            jtxtLights.requestFocus();
        }
        else
        {
           jtxtLights.setEnabled(false);
           jtxtLights.setText("0");
        }
    }//GEN-LAST:event_jChkLightsActionPerformed

    private void jtxtBedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBedActionPerformed

    private void jtxtSofaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSofaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSofaActionPerformed

    private void jtxtChairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChairActionPerformed

    private void jtxtRefrigeratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtRefrigeratorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtRefrigeratorActionPerformed

    private void jtxtFanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFanActionPerformed

    private void jtxtLightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLightsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLightsActionPerformed

    private void jtxtIronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIronActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIronActionPerformed

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        try
        {
            jtxtReceipt.print();
        }
        catch(java.awt.print.PrinterException e){
            System.err.format("No printer found",e.getMessage());
        
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
    private JFrame frame; 
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
         frame=new JFrame("Exit");
				if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Consumer Billing Systems",
						JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION) {
					System.exit(0);
				}
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jtxtBed.setEnabled(false);
        jtxtSofa.setEnabled(false);
        jtxtChair.setEnabled(false);
        jtxtRefrigerator.setEnabled(false);
        jtxtFan.setEnabled(false);
        jtxtLights.setEnabled(false);
        jtxtAirConditioner.setEnabled(false);
        jtxtMicrowaveoven.setEnabled(false);
        jtxtIron.setEnabled(false);
        jtxtTelivision.setEnabled(false);
        
       
        jtxtCustomerRef.setEnabled(false);
       int refs=5015+ (int) (Math.random() * 17238);
       String cRef="";
       cRef+=refs +1560;
       
        
        
        
        
       jtxtCustomerRef.setText(cRef);
       jtxtFirstname.setText(null);
       jtxtSurname.setText(null);
       jtxtAddress.setText(null);
       jtxtEmail.setText(null);
       jtxtPostCode.setText(null);
       jtxtCustomerMo.setText(null);
       jtxtTax.setText(null);
       jtxtSubTotal.setText(null);
       jtxtSubTotal.setText(null);
       jDateChooser1.setDate(null);
      
        
        
    }//GEN-LAST:event_formWindowActivated

    private void jChkIronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkIronActionPerformed
        if(jChkIron.isSelected())
        {
            jtxtIron.setEnabled(true);
            jtxtIron.setText("");
            jtxtIron.requestFocus();
        }
        else
        {
           jtxtIron.setEnabled(false);
           jtxtIron.setText("0");
        }
    }//GEN-LAST:event_jChkIronActionPerformed

    private void jtxtReceiptPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtxtReceiptPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtReceiptPropertyChange

    private void jChkBedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkBedActionPerformed
        if(jChkBed.isSelected())
        {
            jtxtBed.setEnabled(true);
            jtxtBed.setText("");
            jtxtBed.requestFocus();
        }
        else
        {
           jtxtBed.setEnabled(false);
           jtxtBed.setText("0");
        }
    }//GEN-LAST:event_jChkBedActionPerformed

    private void jChkChairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkChairActionPerformed
       if(jChkChair.isSelected())
        {
            jtxtChair.setEnabled(true);
            jtxtChair.setText("");
            jtxtChair.requestFocus();
        }
        else
        {
           jtxtChair.setEnabled(false);
           jtxtChair.setText("0");
        }
    }//GEN-LAST:event_jChkChairActionPerformed

    private void jChkFanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkFanActionPerformed
      if(jChkFan.isSelected())
        {
            jtxtFan.setEnabled(true);
            jtxtFan.setText("");
            jtxtFan.requestFocus();
        }
        else
        {
           jtxtFan.setEnabled(false);
           jtxtFan.setText("0");
        }
    }//GEN-LAST:event_jChkFanActionPerformed

    private void jChkAirConditionerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkAirConditionerActionPerformed
        if(jChkAirConditioner.isSelected())
        {
            jtxtAirConditioner.setEnabled(true);
            jtxtAirConditioner.setText("");
            jtxtAirConditioner.requestFocus();
        }
        else
        {
           jtxtAirConditioner.setEnabled(false);
           jtxtAirConditioner.setText("0");
        }
    }//GEN-LAST:event_jChkAirConditionerActionPerformed

    private void jChkMicrowaveovenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkMicrowaveovenActionPerformed
       if(jChkMicrowaveoven.isSelected())
        {
            jtxtMicrowaveoven.setEnabled(true);
            jtxtMicrowaveoven.setText("");
            jtxtMicrowaveoven.requestFocus();
        }
        else
        {
           jtxtMicrowaveoven.setEnabled(false);
           jtxtMicrowaveoven.setText("0");
        }
    }//GEN-LAST:event_jChkMicrowaveovenActionPerformed

    private void jChkTelivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkTelivisionActionPerformed
      if(jChkTelivision.isSelected())
        {
            jtxtTelivision.setEnabled(true);
            jtxtTelivision.setText("");
            jtxtTelivision.requestFocus();
        }
        else
        {
           jtxtTelivision.setEnabled(false);
           jtxtTelivision.setText("0");
        }
    }//GEN-LAST:event_jChkTelivisionActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        itemcost[0]=Double.parseDouble(jtxtBed.getText())*1900.87;
        itemcost[1]=Double.parseDouble(jtxtSofa.getText())*180;
        itemcost[2]=Double.parseDouble(jtxtChair.getText())*735;
        itemcost[3]=Double.parseDouble(jtxtRefrigerator.getText())*20.9;
        itemcost[4]=Double.parseDouble(jtxtFan.getText())*392.15;
        itemcost[5]=Double.parseDouble(jtxtLights.getText())*4.50;
        itemcost[6]=Double.parseDouble(jtxtAirConditioner.getText())*392.15;
        itemcost[7]=Double.parseDouble(jtxtMicrowaveoven.getText())*385.20;
        itemcost[8]=Double.parseDouble(jtxtIron.getText())*10;
        itemcost[9]=Double.parseDouble(jtxtTelivision.getText())*558.82;

        itemcost[10]= itemcost[0]+ itemcost[1]+ itemcost[2] +itemcost[3]+ itemcost[4];
        itemcost[11]=itemcost[5]+ itemcost[6]+ itemcost[7]+ itemcost[8]+  itemcost[9];

        itemcost[12]=itemcost[10]+itemcost[11];
        iTax=String.format("£ %.2f",itemcost[12/100]);
        iSubTotal=String.format("£ %.2f",itemcost[12]);
        iTotal=String.format("£ %.2f",itemcost[12]+ itemcost[12/100]);
        jtxtTax.setText(iTax);
        jtxtSubTotal.setText(iSubTotal);
        jtxtTotal.setText(iTotal);

        //=====================================================================
        jtxtReceipt.setEnabled(true);
        //=====================================================================
        int refs= 1325+ (int)( Math.random()*4238);

        //=====================================================================
        Calendar timer=Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime=new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate=new SimpleDateFormat("dd-MMM-yyyy");
        Tdate.format(timer.getTime());
        //====================================================================

        jtxtReceipt.append("\t\tHome Inventory Project\n"+
            "Reference:\t\t\t\t" + refs+
            "\n==================================================\t"+

            "\n======================================================\t"+
            "\n Customer Ref :\t\t\t"+ jtxtCustomerRef.getText()+
            "\n Firstname :\t\t\t\t"+ jtxtFirstname.getText()+
            "\n Surname :\t\t\t\t"+ jtxtSurname.getText()+

            "\n Bed :\t\t\t\t"+ jtxtBed.getText()+
            "\n Sofa :\t\t\t\t"+ jtxtSofa.getText()+
            "\n Chair :\t\t\t\t"+ jtxtChair.getText()+
            "\n Refrigerator :\t\t\t\t"+ jtxtRefrigerator.getText()+
            "\n Fan:\t\t\t\t"+ jtxtFan.getText()+
            "\n Lights :\t\t\t\t"+ jtxtLights.getText()+
            "\n Air Conditioner :\t\t\t"+ jtxtAirConditioner.getText()+
            "\n  Microwave Oven :\t\t\t"+ jtxtMicrowaveoven.getText()+
            "\n Iron :\t\t\t\t"+ jtxtIron.getText()+
            "\n Telivision :\t\t\t\t"+ jtxtTelivision.getText()+

            "\n========================================================\t"+

            "\nTax:\t\t\t"+iTax +
            "\nSub Total: \t\t\t"+ iSubTotal +
            "\nTotal :\t\t\t" +iTotal+

            "\n========================================================\t"+
            "\nDate:" +Tdate.format(timer.getTime()) +
            "\t\tTime:" +tTime.format(timer.getTime()) +
            "\n\n\t Thank you for Shopping at Home Inventory Store \n");

    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtBed.setEnabled(false);
        jtxtSofa.setEnabled(false);
        jtxtChair.setEnabled(false);
        jtxtRefrigerator.setEnabled(false);
        jtxtFan.setEnabled(false);
        jtxtLights.setEnabled(false);
        jtxtAirConditioner.setEnabled(false);
        jtxtMicrowaveoven.setEnabled(false);
        jtxtIron.setEnabled(false);
        jtxtTelivision.setEnabled(false);

        jtxtBed.setText("0");
        jtxtSofa.setText("0");
        jtxtChair.setText("0");
        jtxtRefrigerator.setText("0");
        jtxtFan.setText("0");
        jtxtLights.setText("0");
        jtxtAirConditioner.setText("0");
        jtxtMicrowaveoven.setText("0");
        jtxtIron.setText("0");
        jtxtTelivision.setText("0");

        jChkBed.setSelected(false);
        jChkSofa.setSelected(false);
        jChkChair.setSelected(false);
        jChkRefrigerator.setSelected(false);
        jChkFan.setSelected(false);
        jChkLights.setSelected(false);
        jChkAirConditioner.setSelected(false);
        jChkMicrowaveoven.setSelected(false);
        jChkIron.setSelected(false);
        jChkTelivision.setSelected(false);

        jtxtCustomerRef.setText(null);
        jtxtCustomerRef.setEnabled(false);
        int refs=5015+ (int) (Math.random() * 17238);
        String cRef="";
        cRef+=refs +1560;

        jtxtCustomerRef.setText(cRef);
        jtxtFirstname.setText(null);
        jtxtSurname.setText(null);
        jtxtAddress.setText(null);
        jtxtEmail.setText(null);
        jtxtPostCode.setText(null);
        jtxtCustomerMo.setText(null);
        jtxtTax.setText(null);
        jtxtSubTotal.setText(null);
        jtxtSubTotal.setText(null);
        jDateChooser1.setDate(null);
        

    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jtxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmailActionPerformed

    private void jtxtCustomerMoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCustomerMoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCustomerMoActionPerformed

    private void jtxtCustomerRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCustomerRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCustomerRefActionPerformed

    private void jtxtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFirstnameActionPerformed

    private void jtxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAddressActionPerformed

    private void jtxtPostCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPostCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPostCodeActionPerformed

    private void jtxtSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSurnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consumer_Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consumer_Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consumer_Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consumer_Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consumer_Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jChkAirConditioner;
    private javax.swing.JCheckBox jChkBed;
    private javax.swing.JCheckBox jChkChair;
    private javax.swing.JCheckBox jChkFan;
    private javax.swing.JCheckBox jChkIron;
    private javax.swing.JCheckBox jChkLights;
    private javax.swing.JCheckBox jChkMicrowaveoven;
    private javax.swing.JCheckBox jChkRefrigerator;
    private javax.swing.JCheckBox jChkSofa;
    private javax.swing.JCheckBox jChkTelivision;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.toedter.components.JLocaleChooser jLocaleChooser3;
    private com.toedter.components.JLocaleChooser jLocaleChooser4;
    private com.toedter.components.JLocaleChooser jLocaleChooser5;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtAirConditioner;
    private javax.swing.JTextField jtxtBed;
    private javax.swing.JTextField jtxtChair;
    private javax.swing.JTextField jtxtCustomerMo;
    private javax.swing.JTextField jtxtCustomerRef;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFan;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtIron;
    private javax.swing.JTextField jtxtLights;
    private javax.swing.JTextField jtxtMicrowaveoven;
    private javax.swing.JTextField jtxtPostCode;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtRefrigerator;
    private javax.swing.JTextField jtxtSofa;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTelivision;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
